spring.application.name=base-security
base.security.default.pwd=User@6375
base.security.login.password.regexp=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!%*?&])[A-Za-z\\d$@$!%*?&]{8,16}$
base.security.permit.urls=
base.security.login.url=/security/user/login


